Repository mini-project-03/Frontend3, pull requests merged in 2025-05, with the labels that each got.

#4 feat: 로그인/회원가입 페이지 구현 #3
  package-lock.json
  package.json
  public/Line 1.svg
  public/Line 2.svg
  public/image 1.png
  public/image 15.png
  public/image 16.png
  public/register.png
  src/App.tsx
  src/pages/HomePage.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
Labels: enhancement

#9 feat: tailwind 초기세팅 #2
  package-lock.json
  package.json
  postcss.config.js
  src/index.css
  src/main.tsx
  src/pages/HomePage.tsx
  tailwind.config.js
  vite.config.ts
Labels: enhancement

#12 feat: BaseLayout 로 레이아웃 구조 및 Header 컴포넌트 구현
  package-lock.json
  src/App.tsx
  src/components/layout/BaseLayout.tsx
  src/components/layout/Header.tsx
  src/main.tsx
Labels: enhancement

#13 feat: 투표 생성 모달 ui 구현 #8
  package-lock.json
  package.json
  src/components/ui/Modal.tsx
  src/components/ui/VoteFormModal.tsx
  src/pages/HomePage.tsx
  src/stores/uiStore.ts
Labels: enhancement

#16 Feature/#15/modal create vote state
  src/components/vote/VoteFormModal.tsx
  src/data/mockVotes.ts
  src/pages/HomePage.tsx
  src/stores/uiStore.ts
  src/stores/voteStore.ts
  src/types/vote.ts
Labels: enhancement

#27 Feature/#25/confirm modal
  package-lock.json
  package.json
  src/api/authAPI.ts
  src/components/ui/confirmModal.tsx
  src/components/vote/VoteFormModal.tsx
Labels: enhancement

#30 [feature] 투표 상세 모달 (#22)
  public/participants.png
  src/components/FoodItem.tsx
  src/components/vote/ParticipationChart.tsx
  src/components/vote/VoteDetailModal.tsx
  src/components/vote/VoteFormModal.tsx
  src/data/mockParticipants.ts
  src/pages/HomePage.tsx
  src/stores/uiStore.ts
  src/stores/userStore.ts
  src/stores/voteStore.ts
  src/types/user.ts
  src/utils/dateFormatter.ts
  tailwind.config.js
Labels: documentation

#32 [refactor] Vote API 요청 및 응답 타입 분리 및 타입 구조 개선 #29
  src/api/foodAPI.ts
  src/api/voteAPI.ts
  src/components/VoteItem.tsx
  src/components/vote/VoteFormModal.tsx
  src/pages/HomePage.tsx
  src/stores/voteStore.ts
  src/types/vote.ts
Labels: documentation

#36 feat: 인증 체크 커스텀 훅 구현 및 전역 상태관리
  package-lock.json
  package.json
  src/components/VoteItem.tsx
  src/hooks/api/auth/useRequireAuth.ts
  src/main.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/stores/authStore.ts
Labels: enhancement

#40 feat: 투표 생성 폼 파일 구조 분리 및 투표 생성 API 연동 완료(#31)
  src/api/voteAPI.ts
  src/components/vote/detail/ParticipationChart.tsx
  src/components/vote/detail/VoteDetailModal.tsx
  src/components/vote/form/VoteFormContent.tsx
  src/components/vote/form/VoteFormModal.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/stores/authStore.ts
  src/stores/uiStore.ts
  src/stores/userStore.ts
  src/stores/voteStore.ts
  src/utils/dateFormatter.ts
  src/utils/validation.ts
Labels: enhancement

#39 feat: add confirmModal register(#35)
  src/pages/Register.tsx
Labels: enhancement

#46 feat: 카드 클릭 시 결과 모달 표시 및 백그라운드 블러 처리(#44)
  src/App.tsx
  src/pages/RandomMenuBox.tsx
Labels: enhancement

#45 feat: 투표 수정,삭제,마감 기능 및 UI 개선(마감 투표 정렬 및 블러 처리) #38
  package-lock.json
  package.json
  src/api/voteAPI.ts
  src/components/VoteItem.tsx
  src/components/vote/detail/VoteDetailModal.tsx
  src/components/vote/form/VoteFormContent.tsx
  src/components/vote/form/VoteFormModal.tsx
  src/components/vote/item/VoteItem.tsx
  src/components/vote/item/VoteOptionsMenu.tsx
  src/pages/HomePage.tsx
  src/stores/uiStore.ts
  src/stores/voteStore.ts
  src/types/vote.ts
  src/utils/sortVotes.ts
Labels: enhancement

#43 feat: 로그아웃 로직 구현(#42)
  package-lock.json
  src/api/authAPI.ts
  src/components/LogoutButton.tsx
  src/components/layout/Header.tsx
Labels: enhancement

#54 feature/#49/random-menu-roulette
  package-lock.json
  src/components/ui/Roulette/Roulette.tsx
  src/components/ui/Roulette/RouletteItems.tsx
  src/components/ui/Roulette/SelectedItemHighlight.tsx
  src/components/vote/item/VoteItem.tsx
  src/constants/imagePaths.ts
  src/main.tsx
  src/pages/HomePage.tsx
Labels: enhancement

#58 [FEAT] 투표 참여, 참여 취소 시 예외 처리
  package-lock.json
  src/components/vote/detail/VoteDetailModal.tsx
  src/pages/HomePage.tsx
Labels: enhancement

#63 feat: refreshAccessToken 재발급 및 인터셉터 전역 처리
  src/App.tsx
  src/api/apiClient.ts
  src/api/authAPI.ts
  src/api/voteAPI.ts
  src/components/LogoutButton.tsx
  src/pages/SignupPage.tsx
Labels: enhancement

#60 Feature/#51/fixed css momuk
  et --hard f99cfc8b40f2aa769d7ccd10bca3afbddd5bb470
  package-lock.json
  s 수정(#51)
  src/components/auth/AuthLayout.tsx
  src/components/layout/Header.tsx
  src/components/ui/Modal.tsx
  src/components/vote/detail/ParticipationChart.tsx
  src/components/vote/detail/VoteDetailModal.tsx
  src/components/vote/form/VoteFormContent.tsx
  src/components/vote/item/VoteItem.tsx
  src/components/vote/item/VoteOptionsMenu.tsx
Labels: chore

#55 feat: 투표 자동 마감 처리 및 참여자용 결과 확인 기능 구현
  src/components/vote/form/VoteFormModal.tsx
  src/components/vote/item/VoteItem.tsx
  src/stores/voteStore.ts
Labels: enhancement

#67 feat: 투표 이미지 고정 처리 및 VoteAPI 헤더 제거 리팩터링 #62
  src/api/voteAPI.ts
  src/components/vote/item/VoteItem.tsx
Labels: enhancement

#68 feat: 작성자 참여취소 방지 및 투표 생성 폼에 사용자 이름 표시 (#65)
  s 수정(#51)
  src/components/layout/Header.tsx
  src/components/vote/detail/VoteDetailModal.tsx
  src/components/vote/form/VoteFormContent.tsx
Labels: enhancement

#70 feat: 투표 생성 버튼 룰렛 영역에 추가(#66)
  src/components/ui/Roulette/Roulette.tsx
  src/pages/HomePage.tsx
Labels: documentation

#72 feat: 투표 생성 , 삭제 예외 처리
  src/components/vote/detail/VoteDetailModal.tsx
  src/components/vote/form/VoteFormModal.tsx
Labels: enhancement

#71 feat: 투표 수정 시 confirm 모달 중복 표시 현상 제거
  src/components/vote/form/VoteFormModal.tsx
Labels: enhancement

#73 feat: AuthForm에 실시간 유효성 검사 및 제출 조건 로직 추가
  public/signup.png
  src/components/auth/AuthForm.tsx
  src/components/auth/AuthLayout.tsx
  src/components/common/BaseInput.tsx
  src/pages/LoginPage.tsx
  src/pages/SignupPage.tsx
  src/utils/AuthFormValidation.ts
Labels: enhancement

#80 fix: 마감 투표 결과 버튼, toast 처리, 지난 투표 제거
  src/components/vote/detail/VoteDetailModal.tsx
  src/components/vote/form/VoteFormModal.tsx
  src/components/vote/item/VoteItem.tsx
  src/pages/HomePage.tsx
Labels: documentation

#81 chore: 수정 시 경로 재설정
  src/components/vote/form/VoteFormModal.tsx
Labels: chore

#84 chore: 헤더 간격 조정
  src/api/apiClient.ts
  src/components/layout/Header.tsx
Labels: chore

#87 fix: 마감된 투표 참여자 결과 확인 시에만 api 호출 #85
  src/components/vote/item/VoteItem.tsx
Labels: bug

#82 feat: 헤더 사용자 이름 표시, 상세 모달 시간 포맷 수정, 투표 글자 수 제한, 버튼 색상 변경 #77
  src/components/layout/Header.tsx
  src/components/ui/Roulette/Roulette.tsx
  src/components/vote/detail/VoteDetailModal.tsx
  src/components/vote/form/VoteFormContent.tsx
  src/utils/VoteFormValidation.ts
  src/utils/dateFormatter.ts
  tailwind.config.js
Labels: enhancement

#75 feat: 음식 이미지 교체 및 룰렛 이미지 매칭 수정
  public/food1.png
  public/food4.png
  public/food6.png
  public/food9.png
  public/restaurant10.jpg
  public/restaurant11.jpg
  public/restaurant2.jpg
  public/restaurant3.jpg
  public/restaurant4.jpg
  public/restaurant5.jpg
  public/restaurant6.jpg
  public/restaurant7.jpg
  public/restaurant8.jpg
  public/restaurant9.jpg
  public/고기.jpg
  public/김밥.jpg
  public/김치볶음밥.png
  public/떡볶이.jpg
  public/똠양꿍.png
  public/만두.png
  public/비빔밥.png
  public/순두부찌개.jpg
  public/스시.jpg
  public/양곱창.png
  public/엽떡.jpg
  public/일식라멘.png
  public/청년다방.jpg
  public/파스타.png
  public/피자.jpg
  public/해장국.jpg
  src/components/ui/Roulette/Roulette.tsx
  src/components/ui/Roulette/RouletteItems.tsx
  src/components/ui/Roulette/SelectedItemHighlight.tsx
  src/components/vote/item/VoteItem.tsx
  src/constants/imagePaths.ts
Labels: enhancement

#90 fix: 참여/취소 시 참여자 수, 참여율 반영 안 되는 문제 수정 및 deadline 유효성 함수 추가 #89
  src/components/vote/detail/VoteDetailModal.tsx
  src/components/vote/form/VoteFormContent.tsx
  src/utils/VoteFormValidation.ts
Labels: bug

#91 feat: 마감된 투표에서 결과 확인 버튼 노출 및 참여 시 토스트 알림 추가
  src/components/vote/detail/VoteDetailModal.tsx
  src/components/vote/item/VoteItem.tsx
Labels: documentation

#93 feat: 모달 최신 데이터 fetch하여 상태 업데이트 (vote 변경된 경우) #92
  src/components/vote/detail/VoteDetailModal.tsx
  src/components/vote/item/VoteItem.tsx
Labels: enhancement
